# Generated by Django 5.1.2 on 2024-11-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
