# Generated by Django 5.1.2 on 2024-11-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_topping_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='related_pizza',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='related_topping',
        ),
    ]
