# Generated by Django 5.1.7 on 2025-04-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0003_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.TextField(default=""),
        ),
    ]
